# bind address, use empty string to bind to all interfaces
bind_address=""
# backend listen port
listen_port=9999
# proxy protocol port, use 0 to disable
proxyprotocol_port=0
# Server location
server_lat=0
server_lng=0

# geo ip provider ipinfo.io or ip.sb
geo_ip_api_provider="ip.sb"
# ipinfo.io API key, if applicable
ipinfo_api_key=""

# assets directory path, defaults to `assets` in the same directory
assets_path=""

# password for logging into statistics page
statistics_password="DISABLE"

# database type for statistics data, currently supports: none, memory, bolt, mysql, postgresql
# if none is specified, no telemetry/stats will be recorded, and no result PNG will be generated
database_type="bolt"
database_hostname=""
database_name="speedtest"
database_username=""
database_password=""

# if you use `bolt` as database, set database_file to database file location
database_file="speedtest.db"

# TLS and HTTP/2 settings. TLS is required for HTTP/2
enable_tls=false
enable_http2=false

# if you use HTTP/2 or TLS, you need to prepare certificates and private keys
# tls_cert_file="cert.pem"
# tls_key_file="privkey.pem"

# ip every 24h limit traffic limit /GB
ip_daily_traffic_limit=10

# each ip only record one result
same_ip_multi_logs=false

# if behind proxy open it read real ip from x-forwarded-for
enable_xff_ip=false
